image: gradle:8-jdk17-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

quality-gate:
  stage: test
  script: |-
    gradle check
    gradle sonar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push