apiVersion: apps/v1
kind: Deployment
metadata:
  name: std-vsm-history
  namespace: vehiclestatus
  labels:
    app: std-vsm-history
spec:
  replicas: 1
  template:
    metadata:
      name: std-vsm-history
      labels:
        app: std-vsm-history
    spec:
      containers:
        - name: std-vsm-history
          image: std-vsm-history
          command:
            - "java"
            - "-Dspring.profiles.active=$(profile)"
            - "-cp"
            - "@/app/jib-classpath-file"
            - "com.hkmc.vsmhistory.VsmHistoryApplication"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
      restartPolicy: Always
  selector:
    matchLabels:
      app: std-vsm-history

