apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

vars:
  - name: profile
    objref:
      kind: Deployment
      name: std-vsm-history
      apiVersion: apps/v1
    fieldref:
      fieldpath: metadata.labels.profile