apiVersion: v1
name: std-vsm-history
description: std-vsm-history
type: application
version: 1.0.0
appVersion: 1.0.04-us4
icon: https://code.hcloud.hmc.co.kr/uploads/-/system/group/avatar/145/icon.png?width=64
sources:
- https://code.hcloud.hmc.co.kr/ccs/sandbox/vsm-history.git
