image:
  repository: registry.hcloud.hmc.co.kr/ccs/vehiclestatus/std-vsm-history
  pullPolicy: IfNotPresent
  tag: 1.0.04-us4
resources:
  requests:
    cpu: 2000m
    memory: 4Gi
  limits:
    cpu: 2000m
    memory: 4Gi
readinessInitialDelaySeconds: 30
readinessPeriodSeconds: 30
livenessInitialDelaySeconds: 60
livenessPeriodSeconds: 30
jvm:
  enabled: true
  option: -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:InitialRAMPercentage=50
    -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=75
service:
  type: ClusterIP
  port: 8080
  nodePort: 0
  ipamRange: null
  loadbalancerIP: null
replicas: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 70
timezone: Asia/Seoul
autoPromotionEnabled: true
configServer:
  enabled: true
