apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

commonAnnotations:
  business-team: AAAA
  business-owner: "1234567"
  development-team: BBBB
  development-manager: "2345678"
  operation-team: CCCC
  operation-manager: "3456789"
